#!/bin/bash
# Bryant Hansen

# writable fields generated by:
# ./id3ted --frame-list | grep "^\ \ \*" | while read a b c ; do echo $b ; done > writable_fields.lst

TEST_DIR="/tmp/"
ORIGINAL_MEDIA_DIR="${TEST_DIR}/original_media"

if [[ ! -d "$ORIGINAL_MEDIA_DIR" ]] ; then
    mkdir -p "$ORIGINAL_MEDIA_DIR"
fi
if [[ ! -d "$ORIGINAL_MEDIA_DIR" ]] ; then
    echo "ERROR: failed to find or create ORIGINAL_MEDIA_DIR $ORIGINAL_MEDIA_DIR" >&2
    exit 2
fi

#wget http://freemusicarchive.org/music/download/e263a939f306c27e29cdbbd0a8b11a380b2d5628
MP3_URL="http://freemusicarchive.org/music/download/e263a939f306c27e29cdbbd0a8b11a380b2d5628"
MP3_FILE="${ORIGINAL_MEDIA_DIR}/e263a939f306c27e29cdbbd0a8b11a380b2d5628"
if [[ ! -f "${MP3_FILE}" ]] ; then
    if ! pushd "$ORIGINAL_MEDIA_DIR" ; then
        echo "ERROR: failed to change directory to ORIGINAL_MEDIA_DIR $ORIGINAL_MEDIA_DIR" >&2
        exit 3
    fi
    wget http://freemusicarchive.org/music/download/"${MP3_FILE}"
    popd
fi

if [[ ! -f "${MP3_FILE}" ]] ; then
    echo "ERROR: failed to fetch mp3 test file $MP3_URL to local $MP3_FILE" >&2
    exit 4
fi

#if ! pushd "$TEST_DIR" ; then
#    echo "ERROR: failed to change directory to TEST_DIR $TEST_DIR" >&2
#    exit 5
#fi

./test1.sh "$MP3_FILE"
./test1.sh "$MP3_FILE" TBPM
./test1.sh "$MP3_FILE" TBPM 100.12
./test1.sh "$MP3_FILE" TPOP 50

exit $?

